Revert "use data=journal for all root ext4"
This reverts commit 89ecf206ca2cd2cf160ae5d8957520a75952b583.

Unfortunatley it doesn't work, I'll dig into this later:

building all machine configurations...
error: while evaluating the attribute ‘buildCommand’ of the derivation
‘nixops-machines’ at
/nix/store/296nhz86xfa1h8a5yivq3qprvk9nmnc8-nixexprs.tar.xz/pkgs/build-support/trivial-builders.nix:10:14:
while evaluating anonymous function at
/nix/store/399hz2bmc157p4412i718ir4yjb6gd3g-nixops-1.3.1/share/nix/nixops/eval-machine-info.nix:160:46,
called from
/nix/store/296nhz86xfa1h8a5yivq3qprvk9nmnc8-nixexprs.tar.xz/lib/attrsets.nix:165:52:
while evaluating the attribute ‘buildCommand’ of the derivation
‘nixos-system-grindelwald-16.03.802.01f5711’ at
/nix/store/296nhz86xfa1h8a5yivq3qprvk9nmnc8-nixexprs.tar.xz/nixos/modules/system/activation/top-level.nix:102:7:
while evaluating ‘optionalString’ at
/nix/store/296nhz86xfa1h8a5yivq3qprvk9nmnc8-nixexprs.tar.xz/lib/strings.nix:66:26,
called from
/nix/store/296nhz86xfa1h8a5yivq3qprvk9nmnc8-nixexprs.tar.xz/nixos/modules/system/activation/top-level.nix:39:9:
while evaluating the attribute ‘exportReferencesGraph’ of the derivation
‘initrd’ at
/nix/store/296nhz86xfa1h8a5yivq3qprvk9nmnc8-nixexprs.tar.xz/pkgs/build-support/kernel/make-initrd.nix:23:3:
while evaluating the attribute ‘fsInfo’ of the derivation
‘stage-1-init.sh’ at
/nix/store/296nhz86xfa1h8a5yivq3qprvk9nmnc8-nixexprs.tar.xz/pkgs/build-support/substitute/substitute-all.nix:6:3:
while evaluating the attribute ‘text’ of the derivation ‘initrd-fsinfo’
at
/nix/store/296nhz86xfa1h8a5yivq3qprvk9nmnc8-nixexprs.tar.xz/pkgs/build-support/trivial-builders.nix:10:14:
cannot coerce null to a string, at
/nix/store/296nhz86xfa1h8a5yivq3qprvk9nmnc8-nixexprs.tar.xz/nixos/modules/system/boot/stage-1.nix:215:78
error: unable to build all machine configurations